version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: iot-rabbitmq
    ports:
      - "5672:5672"   # Porta do protocolo AMQP
      - "15672:15672" # Porta do painel visual
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}